version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/colorful-starbucks-frontend
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
      environment:
        variables:
          AWS_ACCOUNT_ID: '#{AWS_ACCOUNT_ID}'
          AWS_REGION: '#{AWS_REGION}'
          FRONTEND_ECR_REPOSITORY: '#{FRONTEND_ECR_REPOSITORY}'
